### ISSUE TITLE
USER STORY: Informative Homepage for Users

### ISSUE THREAD

**Issue by BohdanBezushka** [BohdanBezushka/MoneyMate#1]
As a **user**, I can **view a homepage to understand the purpose of the application**, so that **I can benefit from it efficiently.**

## Acceptance Criteria:
* The website provides a description of the application.
* The homepage indicates the steps to use the application.
* On the website, there are user reviews of people who have used the application.

## Tasks
- [ ] Task 1: Add a description of the application.
- [ ] Task 2: Add a description with steps to start using the app.
- [ ] Task 3: Add user reviews.
