### ISSUE TITLE
USER STORY: Download PDF

### ISSUE THREAD

**Issue by BohdanBezushka** [BohdanBezushka/MoneyMate#11]
As a **user**, I can **download all the expense and income records in PDF format** so that **I can benefit from being able to store and access them easily at any time.**

## Acceptance Criteria:
* The user has an option in the menu to export the record of all expenses and incomes in different formats.
* The user can choose the dates to generate the report of expenses and incomes.

## Tasks
- [ ] Task 1: Add a download report option to the user menu.
- [ ] Task 2: The user can choose which type of file they want to download.
- [ ] Task 3:The user can select the exact dates of the records.
