### ISSUE TITLE
USER STORY: Recover password

### ISSUE THREAD

**Issue by BohdanBezushka** [BohdanBezushka/MoneyMate#13]
As a **user**, I can **recover my password in case I forget it**, so that **I can benefit from being able to access my account again without having to create a new one.**

## Acceptance Criteria:
* The user receives an email to recover their password.
* The user can create a new password to access their account.

## Tasks
- [ ] Task 1: Add a password recovery option during the login or registration process for users who forget their login credentials.
- [ ] Task 2: Create a function to send a message to the user's email.
- [ ] Task 3: Create a page where the user can enter a new password to log in.
