### ISSUE TITLE
USER STORY: Origins for incomes

### ISSUE THREAD

**Issue by BohdanBezushka** [BohdanBezushka/MoneyMate#19]
As a **user**, I have **the capability to categorize my incomes**, so that **I can receive the benefit of understanding my spending habits and identifying areas for improvement.**

## Acceptance Criteria:
* The user can choose, create, delete or modify origins for incomes.

## Tasks
- [ ] Task 1: Add an origin option in the user menu.
- [ ] Task 2: Add the possibility to add, modify and delete origins.
- [ ] Task 3: Add pre-established origins for incomes.
