### ISSUE TITLE
USER STORY: Efficient App Navigation

### ISSUE THREAD

**Issue by BohdanBezushka** [BohdanBezushka/MoneyMate#2]
As a **user**, I can **navigate the app easily and intuitively** so that **I can access information efficiently.**

## Acceptance Criteria:
* Access to the website is efficient.
* The tab displays the correct name of the app.
* A favicon appears before the page title in the tab.

## Tasks
- [ ] Task 1: Make an efficient website.
- [ ] Task 2: Add the name app on the tab.
- [ ] Task 3: Add favicon to static files.
