### ISSUE TITLE
USER STORY: Add expense or income

### ISSUE THREAD

**Issue by BohdanBezushka** [BohdanBezushka/MoneyMate#6]
As a **user**, I can **add an expense or income** so that **I have a record.**

## Acceptance Criteria:
* The user can correctly register an expense or income in the application.
* The user can see the records of expenses and incomes that he/she has just made.
* The user can modify any expense or income.
* The user can delete any expense or income.

## Tasks
- [ ] Task 1: Add an option to register an expense or income.
- [ ] Task 2: Add an option to modify an expense or income.
- [ ] Task 3: Add an option to delete an expense or income.
