### ISSUE TITLE
USER STORY: User Financial Balance Visualization

### ISSUE THREAD

**Issue by BohdanBezushka** [BohdanBezushka/MoneyMate#7]
As a **user**, I can **have the capability to view my total expenses and income**, so that I can receive the benefit of seeing my financial balance at a glance.**

## Acceptance Criteria:
* The user can see the total expenses.
* The user can see the total income.
* The user can see the balance.

## Tasks
- [ ] Task 1: Add up all the expenses and display them at the bottom of the application.
- [ ] Task 2: Add up all the incomes and display them at the bottom of the application.
- [ ] Task 3: Add up the expenses and income and display it at the bottom of the application.
