### ISSUE TITLE
USER STORY: Categories for expenses

### ISSUE THREAD

**Issue by BohdanBezushka** [BohdanBezushka/MoneyMate#8]
As a **user**, I have **the capability to categorize my expenses and income**, so that **I can receive the benefit of understanding my spending habits and identifying areas for improvement.**

## Acceptance Criteria:
* The user can choose, create, delete or modify categories for expenses and income.

## Tasks
- [ ] Task 1: Add a categories option in the user menu.
- [ ] Task 2: Add the possibility to add, modify and delete categories.
- [ ] Task 3: Add pre-established categories for expenses and income.
