### ISSUE TITLE
DEVELOPER TASK: Define User Stories and Epics

### ISSUE THREAD

**Issue by BohdanBezushka** [BohdanBezushka/MoneyMate#9]
## Description:
Define user stories and epics.

## Acceptance Criteria:
* The basic User Stories for an MVP are correctly defined.
* The Epics are defined.

## Tasks
- [ ] Task 1: Add User Histories to Issues with the corresponding label, project and milestone.
- [ ] Task 2: Write Epics.
- [ ] Task 3: Add User Histories to Epics.
